# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763e6b5df5eef16a43fe5ae89e315160d156cba822d11639a2fc9af804aa8f796ccbdd5738673707a2736a57cd235f3fa9eddeae968e7a8455f51d7e3802d22b

test:
  secret_key_base: 8f426d5074c638e852294ae473765ae301b754f66bb143c793edc5f5b0e7519aa30590c8ced6b57d0241283b8c10d9e67fdce6e01ee3ba8ccef1e9d54fe8962e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
